const sharedModuleCatalogEntries = [
  {
    schemaCode: "TIMERTICK",
    schemaName: "TimerTick.fbs",
    fileIdentifier: "TICK",
    source: "shared-module-runtime",
  },
  {
    schemaCode: "HTTPREQUEST",
    schemaName: "HttpRequest.fbs",
    fileIdentifier: "HREQ",
    source: "shared-module-runtime",
  },
  {
    schemaCode: "HTTPRESPONSE",
    schemaName: "HttpResponse.fbs",
    fileIdentifier: "HRSP",
    source: "shared-module-runtime",
  },
  {
    schemaCode: "DETACHEDSIGNATURE",
    schemaName: "DetachedSignature.fbs",
    fileIdentifier: "SIGD",
    source: "shared-module-security",
  },
  {
    schemaCode: "FIELDPROTECTIONREQUEST",
    schemaName: "FieldProtectionRequest.fbs",
    fileIdentifier: "FPRQ",
    source: "shared-module-security",
  },
  {
    schemaCode: "FIELDSELECTIONBUNDLE",
    schemaName: "FieldSelectionBundle.fbs",
    fileIdentifier: "FSLB",
    source: "shared-module-security",
  },
  {
    schemaCode: "ENCRYPTEDFIELDSET",
    schemaName: "EncryptedFieldSet.fbs",
    fileIdentifier: "EFLD",
    source: "shared-module-security",
  },
  {
    schemaCode: "ANCHORRADIUSQUERY",
    schemaName: "AnchorRadiusQuery.fbs",
    fileIdentifier: "ARQY",
    source: "shared-module-data",
  },
  {
    schemaCode: "OBSERVATIONBATCH",
    schemaName: "ObservationBatch.fbs",
    fileIdentifier: "OBSV",
    source: "shared-module-data",
  },
  {
    schemaCode: "ASSOCIATIONBATCH",
    schemaName: "AssociationBatch.fbs",
    fileIdentifier: "ASSC",
    source: "shared-module-data",
  },
  {
    schemaCode: "SAMPLEDORBIT",
    schemaName: "SampledOrbit.fbs",
    fileIdentifier: "SAMP",
    source: "shared-module-data",
  },
  {
    schemaCode: "SENSORINPUT",
    schemaName: "SensorInput.fbs",
    fileIdentifier: "SENS",
    source: "shared-module-data",
  },
  {
    schemaCode: "SENSORRESULT",
    schemaName: "SensorResult.fbs",
    fileIdentifier: "SRES",
    source: "shared-module-data",
  },
  {
    schemaCode: "STATEVECTOR",
    schemaName: "StateVector.fbs",
    fileIdentifier: "STVC",
    source: "shared-module-data",
  },
  {
    schemaCode: "STOREDRECORDREF",
    schemaName: "StoredRecordRef.fbs",
    fileIdentifier: "STRF",
    source: "shared-module-data",
  },
  {
    schemaCode: "ALIGNEDRECORDBATCH",
    schemaName: "AlignedRecordBatch.fbs",
    fileIdentifier: "RECS",
    source: "shared-module-data",
  },
  {
    schemaCode: "SQLQUERYREQUEST",
    schemaName: "SqlQueryRequest.fbs",
    fileIdentifier: "SQLQ",
    source: "shared-module-data",
  },
  {
    schemaCode: "SQLQUERYRESULT",
    schemaName: "SqlQueryResult.fbs",
    fileIdentifier: "SQLR",
    source: "shared-module-data",
  },
  {
    schemaCode: "PROTECTEDCATALOGENTRY",
    schemaName: "ProtectedCatalogEntry.fbs",
    fileIdentifier: "PRTC",
    source: "shared-module-data",
  },
  {
    schemaCode: "PROXIMITYSELECTION",
    schemaName: "ProximitySelection.fbs",
    fileIdentifier: "PRXY",
    source: "shared-module-data",
  },
  {
    schemaCode: "CIDREF",
    schemaName: "CidRef.fbs",
    fileIdentifier: "CIDR",
    source: "shared-module-data",
  },
  {
    schemaCode: "UDPDATAGRAM",
    schemaName: "UdpDatagram.fbs",
    fileIdentifier: "UDPG",
    source: "shared-module-runtime",
  },
  {
    schemaCode: "STATEREQUEST",
    schemaName: "StateRequest.fbs",
    fileIdentifier: "SREQ",
    source: "shared-module-runtime",
  },
  {
    schemaCode: "GRAPHDEFINITION",
    schemaName: "GraphDefinition.fbs",
    fileIdentifier: "FGDF",
    source: "orbpro-legacy",
  },
  {
    schemaCode: "WEIGHTEDEDGELIST",
    schemaName: "WeightedEdgeList.fbs",
    fileIdentifier: "FELT",
    source: "orbpro-legacy",
  },
  {
    schemaCode: "CSRGRAPH",
    schemaName: "CSRGraph.fbs",
    fileIdentifier: "FCSR",
    source: "orbpro-legacy",
  },
  {
    schemaCode: "SHORTESTPATHREQUEST",
    schemaName: "ShortestPathRequest.fbs",
    fileIdentifier: "FSPR",
    source: "orbpro-legacy",
  },
  {
    schemaCode: "SHORTESTPATHRESULT",
    schemaName: "ShortestPathResult.fbs",
    fileIdentifier: "FSPS",
    source: "orbpro-legacy",
  },
  {
    schemaCode: "PATHREQUEST",
    schemaName: "PathRequest.fbs",
    fileIdentifier: "FPTR",
    source: "orbpro-legacy",
  },
  {
    schemaCode: "PATHRESULT",
    schemaName: "PathResult.fbs",
    fileIdentifier: "FPTH",
    source: "orbpro-legacy",
  },
  {
    schemaCode: "CATALOGQUERYREQUEST",
    schemaName: "CatalogQueryRequest.fbs",
    fileIdentifier: "CQRQ",
    source: "orbpro-legacy",
  },
  {
    schemaCode: "CATALOGQUERYRESULT",
    schemaName: "CatalogQueryResult.fbs",
    fileIdentifier: "CQRS",
    source: "orbpro-legacy",
  },
  {
    schemaCode: "PROPAGATORBATCHREQUEST",
    schemaName: "PropagatorBatchRequest.fbs",
    fileIdentifier: "PROP",
    source: "orbpro-propagator",
  },
  {
    schemaCode: "PROPAGATORSTATE",
    schemaName: "PropagatorState.fbs",
    fileIdentifier: "PRST",
    source: "orbpro-propagator",
  },
  {
    schemaCode: "ACCESSWINDOWREQUEST",
    schemaName: "AccessWindowRequest.fbs",
    fileIdentifier: "AWRQ",
    source: "orbpro-analysis",
  },
  {
    schemaCode: "ACCESSWINDOWRESULT",
    schemaName: "AccessWindowResult.fbs",
    fileIdentifier: "AWRS",
    source: "orbpro-analysis",
  },
  {
    schemaCode: "COVERAGEGRIDCONFIG",
    schemaName: "CoverageGridConfig.fbs",
    fileIdentifier: "CVGC",
    source: "orbpro-analysis",
  },
  {
    schemaCode: "COVERAGEGRIDINFO",
    schemaName: "CoverageGridInfo.fbs",
    fileIdentifier: "CVGI",
    source: "orbpro-analysis",
  },
  {
    schemaCode: "COVERAGEFOOTPRINTBATCH",
    schemaName: "CoverageFootprintBatch.fbs",
    fileIdentifier: "CVFB",
    source: "orbpro-analysis",
  },
  {
    schemaCode: "COVERAGESTATISTICSRESULT",
    schemaName: "CoverageStatisticsResult.fbs",
    fileIdentifier: "CVST",
    source: "orbpro-analysis",
  },
  {
    schemaCode: "COVERAGEINTERVALSRESULT",
    schemaName: "CoverageIntervalsResult.fbs",
    fileIdentifier: "CVIR",
    source: "orbpro-analysis",
  },
  {
    schemaCode: "COVERAGEFOMRESULT",
    schemaName: "CoverageFomResult.fbs",
    fileIdentifier: "CVFR",
    source: "orbpro-analysis",
  },
  {
    schemaCode: "COVERAGEHEATMAPRESULT",
    schemaName: "CoverageHeatmapResult.fbs",
    fileIdentifier: "CVHR",
    source: "orbpro-analysis",
  },
  {
    schemaCode: "COVERAGEUNIONRESULT",
    schemaName: "CoverageUnionResult.fbs",
    fileIdentifier: "CVUR",
    source: "orbpro-analysis",
  },
  {
    schemaCode: "SWATHFOOTPRINTREQUEST",
    schemaName: "SwathFootprintRequest.fbs",
    fileIdentifier: "SFPQ",
    source: "orbpro-analysis",
  },
  {
    schemaCode: "SWATHFOOTPRINTRESULT",
    schemaName: "SwathFootprintResult.fbs",
    fileIdentifier: "SFPR",
    source: "orbpro-analysis",
  },
  {
    schemaCode: "SWATHGROUNDTRACKREQUEST",
    schemaName: "SwathGroundTrackRequest.fbs",
    fileIdentifier: "SGRQ",
    source: "orbpro-analysis",
  },
  {
    schemaCode: "SWATHGROUNDTRACKRESULT",
    schemaName: "SwathGroundTrackResult.fbs",
    fileIdentifier: "SGRS",
    source: "orbpro-analysis",
  },
  {
    schemaCode: "SWATHGENERATIONREQUEST",
    schemaName: "SwathGenerationRequest.fbs",
    fileIdentifier: "SWAQ",
    source: "orbpro-analysis",
  },
  {
    schemaCode: "SWATHGENERATIONRESULT",
    schemaName: "SwathGenerationResult.fbs",
    fileIdentifier: "SWAS",
    source: "orbpro-analysis",
  },
  {
    schemaCode: "SWATHCONTAINMENTREQUEST",
    schemaName: "SwathContainmentRequest.fbs",
    fileIdentifier: "SPIQ",
    source: "orbpro-analysis",
  },
  {
    schemaCode: "SWATHCONTAINMENTRESULT",
    schemaName: "SwathContainmentResult.fbs",
    fileIdentifier: "SPIR",
    source: "orbpro-analysis",
  },
  {
    schemaCode: "SWATHACCESSREQUEST",
    schemaName: "SwathAccessRequest.fbs",
    fileIdentifier: "SAPQ",
    source: "orbpro-analysis",
  },
  {
    schemaCode: "SWATHACCESSRESULT",
    schemaName: "SwathAccessResult.fbs",
    fileIdentifier: "SAPR",
    source: "orbpro-analysis",
  },
];

export const sharedModuleCatalog = Object.freeze(sharedModuleCatalogEntries);
