const sharedModuleCatalogEntries = [
  {
    schemaCode: "TIMERTICK",
    schemaName: "TimerTick.fbs",
    fileIdentifier: "TICK",
    source: "shared-module-runtime",
  },
  {
    schemaCode: "HTTPREQUEST",
    schemaName: "HttpRequest.fbs",
    fileIdentifier: "HREQ",
    source: "shared-module-runtime",
  },
  {
    schemaCode: "HTTPRESPONSE",
    schemaName: "HttpResponse.fbs",
    fileIdentifier: "HRSP",
    source: "shared-module-runtime",
  },
  {
    schemaCode: "DETACHEDSIGNATURE",
    schemaName: "DetachedSignature.fbs",
    fileIdentifier: "SIGD",
    source: "shared-module-security",
  },
  {
    schemaCode: "FIELDPROTECTIONREQUEST",
    schemaName: "FieldProtectionRequest.fbs",
    fileIdentifier: "FPRQ",
    source: "shared-module-security",
  },
  {
    schemaCode: "FIELDSELECTIONBUNDLE",
    schemaName: "FieldSelectionBundle.fbs",
    fileIdentifier: "FSLB",
    source: "shared-module-security",
  },
  {
    schemaCode: "ENCRYPTEDFIELDSET",
    schemaName: "EncryptedFieldSet.fbs",
    fileIdentifier: "EFLD",
    source: "shared-module-security",
  },
  {
    schemaCode: "ANCHORRADIUSQUERY",
    schemaName: "AnchorRadiusQuery.fbs",
    fileIdentifier: "ARQY",
    source: "shared-module-data",
  },
  {
    schemaCode: "OBSERVATIONBATCH",
    schemaName: "ObservationBatch.fbs",
    fileIdentifier: "OBSV",
    source: "shared-module-data",
  },
  {
    schemaCode: "ASSOCIATIONBATCH",
    schemaName: "AssociationBatch.fbs",
    fileIdentifier: "ASSC",
    source: "shared-module-data",
  },
  {
    schemaCode: "SAMPLEDORBIT",
    schemaName: "SampledOrbit.fbs",
    fileIdentifier: "SAMP",
    source: "shared-module-data",
  },
  {
    schemaCode: "SENSORINPUT",
    schemaName: "SensorInput.fbs",
    fileIdentifier: "SENS",
    source: "shared-module-data",
  },
  {
    schemaCode: "SENSORRESULT",
    schemaName: "SensorResult.fbs",
    fileIdentifier: "SRES",
    source: "shared-module-data",
  },
  {
    schemaCode: "STATEVECTOR",
    schemaName: "StateVector.fbs",
    fileIdentifier: "STVC",
    source: "shared-module-data",
  },
  {
    schemaCode: "STOREDRECORDREF",
    schemaName: "StoredRecordRef.fbs",
    fileIdentifier: "STRF",
    source: "shared-module-data",
  },
  {
    schemaCode: "ALIGNEDRECORDBATCH",
    schemaName: "AlignedRecordBatch.fbs",
    fileIdentifier: "RECS",
    source: "shared-module-data",
  },
  {
    schemaCode: "SQLQUERYREQUEST",
    schemaName: "SqlQueryRequest.fbs",
    fileIdentifier: "SQLQ",
    source: "shared-module-data",
  },
  {
    schemaCode: "SQLQUERYRESULT",
    schemaName: "SqlQueryResult.fbs",
    fileIdentifier: "SQLR",
    source: "shared-module-data",
  },
  {
    schemaCode: "PROTECTEDCATALOGENTRY",
    schemaName: "ProtectedCatalogEntry.fbs",
    fileIdentifier: "PRTC",
    source: "shared-module-data",
  },
  {
    schemaCode: "PROXIMITYSELECTION",
    schemaName: "ProximitySelection.fbs",
    fileIdentifier: "PRXY",
    source: "shared-module-data",
  },
  {
    schemaCode: "CIDREF",
    schemaName: "CidRef.fbs",
    fileIdentifier: "CIDR",
    source: "shared-module-data",
  },
  {
    schemaCode: "UDPDATAGRAM",
    schemaName: "UdpDatagram.fbs",
    fileIdentifier: "UDPG",
    source: "shared-module-runtime",
  },
  {
    schemaCode: "STATEREQUEST",
    schemaName: "StateRequest.fbs",
    fileIdentifier: "SREQ",
    source: "shared-module-runtime",
  },
  {
    schemaCode: "PROPAGATORBATCHREQUEST",
    schemaName: "PropagatorBatchRequest.fbs",
    fileIdentifier: "PROP",
    source: "orbpro-propagator",
  },
  {
    schemaCode: "PROPAGATORSTATE",
    schemaName: "PropagatorState.fbs",
    fileIdentifier: "PRST",
    source: "orbpro-propagator",
  },
];

export const sharedModuleCatalog = Object.freeze(sharedModuleCatalogEntries);
